spring.application.name=GestiondeProductos


# URL de conexión a la base de datos en memoria llamada "bibliotecadb"
spring.datasource.url=jdbc:h2:mem:GestiondeProductos
# Controlador que permite a Java comunicarse con H2
spring.datasource.driverClassName=org.h2.Driver
# Usuario por defecto de H2
spring.datasource.username=sa
# Contraseña en blanco por defecto
spring.datasource.password=
# Le indica a Spring el tipo de base de datos que estamos usando
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Instruye a la base de datos para que actualice su estructura automáticamente según nuestro código
spring.jpa.hibernate.ddl-auto=update
# Habilita una consola web para ver la base de datos en el navegador
spring.h2.console.enabled=true